// File generated from our OpenAPI spec by Stainless.

package com.browserbase.api.models.sessions

import com.browserbase.api.core.JsonValue
import com.browserbase.api.core.http.Headers
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SessionStartParamsTest {

    @Test
    fun create() {
        SessionStartParams.builder()
            .xLanguage(SessionStartParams.XLanguage.TYPESCRIPT)
            .xSdkVersion("3.0.6")
            .xSentAt(OffsetDateTime.parse("2025-01-15T10:30:00.000Z"))
            .xStreamResponse(SessionStartParams.XStreamResponse.TRUE)
            .modelName("gpt-4o")
            .actTimeoutMs(30000.0)
            .browser(
                SessionStartParams.Browser.builder()
                    .cdpUrl("ws://localhost:9222")
                    .launchOptions(
                        SessionStartParams.Browser.LaunchOptions.builder()
                            .acceptDownloads(true)
                            .addArg("string")
                            .cdpUrl("cdpUrl")
                            .chromiumSandbox(true)
                            .connectTimeoutMs(0.0)
                            .deviceScaleFactor(0.0)
                            .devtools(true)
                            .downloadsPath("downloadsPath")
                            .executablePath("executablePath")
                            .hasTouch(true)
                            .headless(true)
                            .ignoreDefaultArgs(true)
                            .ignoreHttpsErrors(true)
                            .locale("locale")
                            .preserveUserDataDir(true)
                            .proxy(
                                SessionStartParams.Browser.LaunchOptions.Proxy.builder()
                                    .server("server")
                                    .bypass("bypass")
                                    .password("password")
                                    .username("username")
                                    .build()
                            )
                            .userDataDir("userDataDir")
                            .viewport(
                                SessionStartParams.Browser.LaunchOptions.Viewport.builder()
                                    .height(0.0)
                                    .width(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .type(SessionStartParams.Browser.Type.LOCAL)
                    .build()
            )
            .browserbaseSessionCreateParams(
                SessionStartParams.BrowserbaseSessionCreateParams.builder()
                    .browserSettings(
                        SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings.builder()
                            .advancedStealth(true)
                            .blockAds(true)
                            .context(
                                SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings
                                    .Context
                                    .builder()
                                    .id("id")
                                    .persist(true)
                                    .build()
                            )
                            .extensionId("extensionId")
                            .fingerprint(
                                SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings
                                    .Fingerprint
                                    .builder()
                                    .addBrowser(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .Browser
                                            .CHROME
                                    )
                                    .addDevice(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .Device
                                            .DESKTOP
                                    )
                                    .httpVersion(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .HttpVersion
                                            ._1
                                    )
                                    .addLocale("string")
                                    .addOperatingSystem(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .OperatingSystem
                                            .ANDROID
                                    )
                                    .screen(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .Screen
                                            .builder()
                                            .maxHeight(0.0)
                                            .maxWidth(0.0)
                                            .minHeight(0.0)
                                            .minWidth(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .logSession(true)
                            .recordSession(true)
                            .solveCaptchas(true)
                            .viewport(
                                SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings
                                    .Viewport
                                    .builder()
                                    .height(0.0)
                                    .width(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .extensionId("extensionId")
                    .keepAlive(true)
                    .projectId("projectId")
                    .proxies(true)
                    .region(SessionStartParams.BrowserbaseSessionCreateParams.Region.US_WEST_2)
                    .timeout(0.0)
                    .userMetadata(
                        SessionStartParams.BrowserbaseSessionCreateParams.UserMetadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
            .browserbaseSessionId("browserbaseSessionID")
            .debugDom(true)
            .domSettleTimeoutMs(5000.0)
            .experimental(true)
            .selfHeal(true)
            .systemPrompt("systemPrompt")
            .verbose(SessionStartParams.Verbose._1)
            .waitForCaptchaSolves(true)
            .build()
    }

    @Test
    fun headers() {
        val params =
            SessionStartParams.builder()
                .xLanguage(SessionStartParams.XLanguage.TYPESCRIPT)
                .xSdkVersion("3.0.6")
                .xSentAt(OffsetDateTime.parse("2025-01-15T10:30:00.000Z"))
                .xStreamResponse(SessionStartParams.XStreamResponse.TRUE)
                .modelName("gpt-4o")
                .actTimeoutMs(30000.0)
                .browser(
                    SessionStartParams.Browser.builder()
                        .cdpUrl("ws://localhost:9222")
                        .launchOptions(
                            SessionStartParams.Browser.LaunchOptions.builder()
                                .acceptDownloads(true)
                                .addArg("string")
                                .cdpUrl("cdpUrl")
                                .chromiumSandbox(true)
                                .connectTimeoutMs(0.0)
                                .deviceScaleFactor(0.0)
                                .devtools(true)
                                .downloadsPath("downloadsPath")
                                .executablePath("executablePath")
                                .hasTouch(true)
                                .headless(true)
                                .ignoreDefaultArgs(true)
                                .ignoreHttpsErrors(true)
                                .locale("locale")
                                .preserveUserDataDir(true)
                                .proxy(
                                    SessionStartParams.Browser.LaunchOptions.Proxy.builder()
                                        .server("server")
                                        .bypass("bypass")
                                        .password("password")
                                        .username("username")
                                        .build()
                                )
                                .userDataDir("userDataDir")
                                .viewport(
                                    SessionStartParams.Browser.LaunchOptions.Viewport.builder()
                                        .height(0.0)
                                        .width(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .type(SessionStartParams.Browser.Type.LOCAL)
                        .build()
                )
                .browserbaseSessionCreateParams(
                    SessionStartParams.BrowserbaseSessionCreateParams.builder()
                        .browserSettings(
                            SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings
                                .builder()
                                .advancedStealth(true)
                                .blockAds(true)
                                .context(
                                    SessionStartParams.BrowserbaseSessionCreateParams
                                        .BrowserSettings
                                        .Context
                                        .builder()
                                        .id("id")
                                        .persist(true)
                                        .build()
                                )
                                .extensionId("extensionId")
                                .fingerprint(
                                    SessionStartParams.BrowserbaseSessionCreateParams
                                        .BrowserSettings
                                        .Fingerprint
                                        .builder()
                                        .addBrowser(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .Browser
                                                .CHROME
                                        )
                                        .addDevice(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .Device
                                                .DESKTOP
                                        )
                                        .httpVersion(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .HttpVersion
                                                ._1
                                        )
                                        .addLocale("string")
                                        .addOperatingSystem(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .OperatingSystem
                                                .ANDROID
                                        )
                                        .screen(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .Screen
                                                .builder()
                                                .maxHeight(0.0)
                                                .maxWidth(0.0)
                                                .minHeight(0.0)
                                                .minWidth(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .logSession(true)
                                .recordSession(true)
                                .solveCaptchas(true)
                                .viewport(
                                    SessionStartParams.BrowserbaseSessionCreateParams
                                        .BrowserSettings
                                        .Viewport
                                        .builder()
                                        .height(0.0)
                                        .width(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .extensionId("extensionId")
                        .keepAlive(true)
                        .projectId("projectId")
                        .proxies(true)
                        .region(SessionStartParams.BrowserbaseSessionCreateParams.Region.US_WEST_2)
                        .timeout(0.0)
                        .userMetadata(
                            SessionStartParams.BrowserbaseSessionCreateParams.UserMetadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .browserbaseSessionId("browserbaseSessionID")
                .debugDom(true)
                .domSettleTimeoutMs(5000.0)
                .experimental(true)
                .selfHeal(true)
                .systemPrompt("systemPrompt")
                .verbose(SessionStartParams.Verbose._1)
                .waitForCaptchaSolves(true)
                .build()

        val headers = params._headers()

        assertThat(headers)
            .isEqualTo(
                Headers.builder()
                    .put("x-language", "typescript")
                    .put("x-sdk-version", "3.0.6")
                    .put("x-sent-at", "2025-01-15T10:30:00.000Z")
                    .put("x-stream-response", "true")
                    .build()
            )
    }

    @Test
    fun headersWithoutOptionalFields() {
        val params = SessionStartParams.builder().modelName("gpt-4o").build()

        val headers = params._headers()

        assertThat(headers).isEqualTo(Headers.builder().build())
    }

    @Test
    fun body() {
        val params =
            SessionStartParams.builder()
                .xLanguage(SessionStartParams.XLanguage.TYPESCRIPT)
                .xSdkVersion("3.0.6")
                .xSentAt(OffsetDateTime.parse("2025-01-15T10:30:00.000Z"))
                .xStreamResponse(SessionStartParams.XStreamResponse.TRUE)
                .modelName("gpt-4o")
                .actTimeoutMs(30000.0)
                .browser(
                    SessionStartParams.Browser.builder()
                        .cdpUrl("ws://localhost:9222")
                        .launchOptions(
                            SessionStartParams.Browser.LaunchOptions.builder()
                                .acceptDownloads(true)
                                .addArg("string")
                                .cdpUrl("cdpUrl")
                                .chromiumSandbox(true)
                                .connectTimeoutMs(0.0)
                                .deviceScaleFactor(0.0)
                                .devtools(true)
                                .downloadsPath("downloadsPath")
                                .executablePath("executablePath")
                                .hasTouch(true)
                                .headless(true)
                                .ignoreDefaultArgs(true)
                                .ignoreHttpsErrors(true)
                                .locale("locale")
                                .preserveUserDataDir(true)
                                .proxy(
                                    SessionStartParams.Browser.LaunchOptions.Proxy.builder()
                                        .server("server")
                                        .bypass("bypass")
                                        .password("password")
                                        .username("username")
                                        .build()
                                )
                                .userDataDir("userDataDir")
                                .viewport(
                                    SessionStartParams.Browser.LaunchOptions.Viewport.builder()
                                        .height(0.0)
                                        .width(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .type(SessionStartParams.Browser.Type.LOCAL)
                        .build()
                )
                .browserbaseSessionCreateParams(
                    SessionStartParams.BrowserbaseSessionCreateParams.builder()
                        .browserSettings(
                            SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings
                                .builder()
                                .advancedStealth(true)
                                .blockAds(true)
                                .context(
                                    SessionStartParams.BrowserbaseSessionCreateParams
                                        .BrowserSettings
                                        .Context
                                        .builder()
                                        .id("id")
                                        .persist(true)
                                        .build()
                                )
                                .extensionId("extensionId")
                                .fingerprint(
                                    SessionStartParams.BrowserbaseSessionCreateParams
                                        .BrowserSettings
                                        .Fingerprint
                                        .builder()
                                        .addBrowser(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .Browser
                                                .CHROME
                                        )
                                        .addDevice(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .Device
                                                .DESKTOP
                                        )
                                        .httpVersion(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .HttpVersion
                                                ._1
                                        )
                                        .addLocale("string")
                                        .addOperatingSystem(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .OperatingSystem
                                                .ANDROID
                                        )
                                        .screen(
                                            SessionStartParams.BrowserbaseSessionCreateParams
                                                .BrowserSettings
                                                .Fingerprint
                                                .Screen
                                                .builder()
                                                .maxHeight(0.0)
                                                .maxWidth(0.0)
                                                .minHeight(0.0)
                                                .minWidth(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .logSession(true)
                                .recordSession(true)
                                .solveCaptchas(true)
                                .viewport(
                                    SessionStartParams.BrowserbaseSessionCreateParams
                                        .BrowserSettings
                                        .Viewport
                                        .builder()
                                        .height(0.0)
                                        .width(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .extensionId("extensionId")
                        .keepAlive(true)
                        .projectId("projectId")
                        .proxies(true)
                        .region(SessionStartParams.BrowserbaseSessionCreateParams.Region.US_WEST_2)
                        .timeout(0.0)
                        .userMetadata(
                            SessionStartParams.BrowserbaseSessionCreateParams.UserMetadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .browserbaseSessionId("browserbaseSessionID")
                .debugDom(true)
                .domSettleTimeoutMs(5000.0)
                .experimental(true)
                .selfHeal(true)
                .systemPrompt("systemPrompt")
                .verbose(SessionStartParams.Verbose._1)
                .waitForCaptchaSolves(true)
                .build()

        val body = params._body()

        assertThat(body.modelName()).isEqualTo("gpt-4o")
        assertThat(body.actTimeoutMs()).isEqualTo(30000.0)
        assertThat(body.browser())
            .isEqualTo(
                SessionStartParams.Browser.builder()
                    .cdpUrl("ws://localhost:9222")
                    .launchOptions(
                        SessionStartParams.Browser.LaunchOptions.builder()
                            .acceptDownloads(true)
                            .addArg("string")
                            .cdpUrl("cdpUrl")
                            .chromiumSandbox(true)
                            .connectTimeoutMs(0.0)
                            .deviceScaleFactor(0.0)
                            .devtools(true)
                            .downloadsPath("downloadsPath")
                            .executablePath("executablePath")
                            .hasTouch(true)
                            .headless(true)
                            .ignoreDefaultArgs(true)
                            .ignoreHttpsErrors(true)
                            .locale("locale")
                            .preserveUserDataDir(true)
                            .proxy(
                                SessionStartParams.Browser.LaunchOptions.Proxy.builder()
                                    .server("server")
                                    .bypass("bypass")
                                    .password("password")
                                    .username("username")
                                    .build()
                            )
                            .userDataDir("userDataDir")
                            .viewport(
                                SessionStartParams.Browser.LaunchOptions.Viewport.builder()
                                    .height(0.0)
                                    .width(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .type(SessionStartParams.Browser.Type.LOCAL)
                    .build()
            )
        assertThat(body.browserbaseSessionCreateParams())
            .isEqualTo(
                SessionStartParams.BrowserbaseSessionCreateParams.builder()
                    .browserSettings(
                        SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings.builder()
                            .advancedStealth(true)
                            .blockAds(true)
                            .context(
                                SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings
                                    .Context
                                    .builder()
                                    .id("id")
                                    .persist(true)
                                    .build()
                            )
                            .extensionId("extensionId")
                            .fingerprint(
                                SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings
                                    .Fingerprint
                                    .builder()
                                    .addBrowser(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .Browser
                                            .CHROME
                                    )
                                    .addDevice(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .Device
                                            .DESKTOP
                                    )
                                    .httpVersion(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .HttpVersion
                                            ._1
                                    )
                                    .addLocale("string")
                                    .addOperatingSystem(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .OperatingSystem
                                            .ANDROID
                                    )
                                    .screen(
                                        SessionStartParams.BrowserbaseSessionCreateParams
                                            .BrowserSettings
                                            .Fingerprint
                                            .Screen
                                            .builder()
                                            .maxHeight(0.0)
                                            .maxWidth(0.0)
                                            .minHeight(0.0)
                                            .minWidth(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .logSession(true)
                            .recordSession(true)
                            .solveCaptchas(true)
                            .viewport(
                                SessionStartParams.BrowserbaseSessionCreateParams.BrowserSettings
                                    .Viewport
                                    .builder()
                                    .height(0.0)
                                    .width(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .extensionId("extensionId")
                    .keepAlive(true)
                    .projectId("projectId")
                    .proxies(true)
                    .region(SessionStartParams.BrowserbaseSessionCreateParams.Region.US_WEST_2)
                    .timeout(0.0)
                    .userMetadata(
                        SessionStartParams.BrowserbaseSessionCreateParams.UserMetadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(body.browserbaseSessionId()).isEqualTo("browserbaseSessionID")
        assertThat(body.debugDom()).isEqualTo(true)
        assertThat(body.domSettleTimeoutMs()).isEqualTo(5000.0)
        assertThat(body.experimental()).isEqualTo(true)
        assertThat(body.selfHeal()).isEqualTo(true)
        assertThat(body.systemPrompt()).isEqualTo("systemPrompt")
        assertThat(body.verbose()).isEqualTo(SessionStartParams.Verbose._1)
        assertThat(body.waitForCaptchaSolves()).isEqualTo(true)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = SessionStartParams.builder().modelName("gpt-4o").build()

        val body = params._body()

        assertThat(body.modelName()).isEqualTo("gpt-4o")
    }
}
